[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  functions = "functions/"
  publish = "dist"
  command = "npm run install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200